-- CreateTable
CREATE TABLE "ContentSeries" (
    "id" TEXT NOT NULL,
    "vehicleId" TEXT,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'Planning',
    "primaryPlatform" TEXT,
    "createdById" TEXT,
    "updatedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ContentSeries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Episode" (
    "id" TEXT NOT NULL,
    "seriesId" TEXT,
    "vehicleId" TEXT,
    "projectId" TEXT,
    "number" INTEGER,
    "title" TEXT NOT NULL,
    "concept" TEXT,
    "stage" TEXT NOT NULL DEFAULT 'Concept',
    "filmDate" TIMESTAMP(3),
    "editDueDate" TIMESTAMP(3),
    "plannedPublishDate" TIMESTAMP(3),
    "publishedDate" TIMESTAMP(3),
    "runtimeMinutes" INTEGER,
    "productionCostCents" INTEGER,
    "cameraMemberId" TEXT,
    "editorMemberId" TEXT,
    "youtubeUrl" TEXT,
    "notes" TEXT,
    "createdById" TEXT,
    "updatedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Episode_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SocialPost" (
    "id" TEXT NOT NULL,
    "episodeId" TEXT,
    "vehicleId" TEXT,
    "platform" TEXT NOT NULL,
    "kind" TEXT NOT NULL DEFAULT 'Post',
    "status" TEXT NOT NULL DEFAULT 'Idea',
    "title" TEXT NOT NULL,
    "caption" TEXT,
    "scheduledDate" TIMESTAMP(3),
    "publishedDate" TIMESTAMP(3),
    "autoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdById" TEXT,
    "updatedById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "SocialPost_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ContentRevenue" (
    "id" TEXT NOT NULL,
    "episodeId" TEXT,
    "vehicleId" TEXT,
    "source" TEXT NOT NULL,
    "amountCents" INTEGER NOT NULL,
    "date" TIMESTAMP(3),
    "description" TEXT,
    "createdById" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ContentRevenue_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "ContentSeries_vehicleId_idx" ON "ContentSeries"("vehicleId");

-- CreateIndex
CREATE INDEX "ContentSeries_status_idx" ON "ContentSeries"("status");

-- CreateIndex
CREATE INDEX "Episode_seriesId_idx" ON "Episode"("seriesId");

-- CreateIndex
CREATE INDEX "Episode_vehicleId_idx" ON "Episode"("vehicleId");

-- CreateIndex
CREATE INDEX "Episode_stage_idx" ON "Episode"("stage");

-- CreateIndex
CREATE INDEX "SocialPost_episodeId_idx" ON "SocialPost"("episodeId");

-- CreateIndex
CREATE INDEX "SocialPost_platform_idx" ON "SocialPost"("platform");

-- CreateIndex
CREATE INDEX "SocialPost_status_idx" ON "SocialPost"("status");

-- CreateIndex
CREATE INDEX "ContentRevenue_episodeId_idx" ON "ContentRevenue"("episodeId");

-- CreateIndex
CREATE INDEX "ContentRevenue_source_idx" ON "ContentRevenue"("source");

-- AddForeignKey
ALTER TABLE "Episode" ADD CONSTRAINT "Episode_seriesId_fkey" FOREIGN KEY ("seriesId") REFERENCES "ContentSeries"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SocialPost" ADD CONSTRAINT "SocialPost_episodeId_fkey" FOREIGN KEY ("episodeId") REFERENCES "Episode"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "ContentRevenue" ADD CONSTRAINT "ContentRevenue_episodeId_fkey" FOREIGN KEY ("episodeId") REFERENCES "Episode"("id") ON DELETE SET NULL ON UPDATE CASCADE;

