"use server";

import { revalidatePath } from "next/cache";
import { requireAuthWithPermission } from "@/lib/auth";
import { createSocialPost, generatePostSetForEpisode } from "@/server/services/media";

export interface FormResult { ok?: boolean; error?: string; message?: string }

const str = (v: FormDataEntryValue | null) => {
  const s = String(v ?? "").trim();
  return s === "" ? null : s;
};
const dt = (v: FormDataEntryValue | null) => {
  const s = String(v ?? "").trim();
  return s === "" ? null : new Date(s);
};

export async function addPostAction(_p: FormResult, fd: FormData): Promise<FormResult> {
  const ctx = await requireAuthWithPermission("media:write");
  const title = String(fd.get("title") ?? "").trim();
  const platform = String(fd.get("platform") ?? "").trim();
  if (!title) return { error: "Title is required." };
  if (!platform) return { error: "Platform is required." };
  try {
    await createSocialPost(ctx, {
      title,
      platform,
      kind: String(fd.get("kind") || "Post"),
      status: String(fd.get("status") || "Idea"),
      episodeId: str(fd.get("episodeId")),
      vehicleId: str(fd.get("vehicleId")),
      caption: str(fd.get("caption")),
      scheduledDate: dt(fd.get("scheduledDate")),
      publishedDate: dt(fd.get("publishedDate")),
      autoGenerated: false,
    });
  } catch (e) {
    return { error: e instanceof Error ? e.message : "Failed." };
  }
  revalidatePath("/os/social");
  revalidatePath("/os/calendar");
  return { ok: true };
}

export async function generatePostSetAction(_p: FormResult, fd: FormData): Promise<FormResult> {
  const ctx = await requireAuthWithPermission("media:write");
  const episodeId = String(fd.get("episodeId") ?? "").trim();
  if (!episodeId) return { error: "Pick an episode." };
  try {
    const created = await generatePostSetForEpisode(ctx, episodeId);
    revalidatePath("/os/social");
    revalidatePath("/os/calendar");
    return { ok: true, message: created === 0 ? "All standard posts already exist for this episode." : `Generated ${created} post${created === 1 ? "" : "s"}.` };
  } catch (e) {
    return { error: e instanceof Error ? e.message : "Failed." };
  }
}
