import { requireAuthWithPermission } from "@/lib/auth";
import { can } from "@/lib/rbac";
import { prisma } from "@/lib/prisma";
import { PageHeader, Panel, MetricCard, StatusBadge, EmptyState } from "@/components/ui/primitives";
import { listSocialPosts, listEpisodesForSelect } from "@/server/services/media";
import { AddPostButton, GeneratePostSetButton } from "./SocialForms";

function fmtDate(d: Date | null | undefined) {
  return d ? d.toISOString().slice(0, 10) : "—";
}

export default async function SocialPage() {
  const ctx = await requireAuthWithPermission("media:read");
  const canWrite = can(ctx, "media:write");

  const data = await listSocialPosts(ctx);
  const [episodeOpts, vehicleRows] = canWrite
    ? await Promise.all([
        listEpisodesForSelect(ctx),
        prisma.vehicle.findMany({ select: { id: true, year: true, make: true, model: true }, orderBy: { year: "asc" } }),
      ])
    : [[], []];
  const episodes = episodeOpts.map((e) => ({ id: e.id, name: e.title }));
  const vehicles = vehicleRows.map((v) => ({ id: v.id, label: `${v.year} ${v.make} ${v.model}` }));

  const maxFunnel = Math.max(1, ...data.funnel.map((b) => b.count));

  return (
    <div>
      <PageHeader
        eyebrow="Content"
        title="Social Media"
        subtitle="Multi-platform publishing pipeline — idea to published, with episode-driven post sets flowing to the calendar."
        actions={canWrite ? (
          <div className="flex gap-2">
            <GeneratePostSetButton episodes={episodes} />
            <AddPostButton episodes={episodes} vehicles={vehicles} />
          </div>
        ) : undefined}
      />

      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <MetricCard label="Total Posts" value={data.posts.length} accent="media" />
        <MetricCard label="In Sponsor Review" value={data.reviewCount} tone={data.reviewCount > 0 ? "attention" : undefined} />
        <MetricCard label="Scheduled" value={data.scheduledCount} accent="sponsor" />
        <MetricCard label="Published" value={data.publishedCount} tone="healthy" />
      </div>

      {/* Publishing funnel */}
      <Panel className="mt-6" title="Publishing Pipeline" accent="media">
        <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">
          {data.funnel.map((b) => (
            <div key={b.stage} className="panel p-3">
              <div className="text-[11px] uppercase tracking-wide text-paper-muted">{b.stage}</div>
              <div className="tnum mt-0.5 font-display text-2xl text-paper-warm">{b.count}</div>
              <div className="mt-2 h-1.5 w-full overflow-hidden rounded-full bg-bg-gunmetal">
                <div className="h-full rounded-full bg-cal-content" style={{ width: `${Math.round((b.count / maxFunnel) * 100)}%` }} />
              </div>
            </div>
          ))}
        </div>
      </Panel>

      {/* Posts */}
      <Panel className="mt-6" title="Posts">
        {data.posts.length === 0 ? (
          <EmptyState title="No posts yet" description="Add a post directly, or generate a full multi-platform set from an episode." />
        ) : (
          <div className="scroll-steel overflow-x-auto">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Title</th><th>Platform</th><th>Kind</th><th>Episode</th>
                  <th>Scheduled</th><th>Published</th><th>Status</th>
                </tr>
              </thead>
              <tbody>
                {data.posts.map((p) => (
                  <tr key={p.id}>
                    <td className="text-paper-warm">
                      {p.title}
                      {p.autoGenerated && <span className="ml-2 text-[10px] uppercase tracking-wide text-paper-muted">auto</span>}
                    </td>
                    <td className="text-paper-steel">{p.platform}</td>
                    <td className="text-paper-muted">{p.kind}</td>
                    <td className="text-paper-muted">{p.episodeTitle ?? "—"}</td>
                    <td className="text-paper-muted">{fmtDate(p.scheduledDate)}</td>
                    <td className="text-paper-muted">{fmtDate(p.publishedDate)}</td>
                    <td><StatusBadge status={p.status} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Panel>

      <p className="mt-4 text-xs text-paper-muted">
        Every episode spawns a standard post set across YouTube, Shorts, Reels, TikTok, Facebook, and email.
        Posts move Idea → Draft → Creative Ready → Sponsor Review → Scheduled → Published, and scheduled
        posts land on the Master Calendar.
      </p>
    </div>
  );
}
